dependencies:
  flutter:
    sdk: flutter
  # For HTTP requests
  http: ^1.1.0
  # For Hex string manipulation
  hex: ^0.2.0
  # Provides Keccak256, Secp256k1, and Address utilities
  web3dart: ^2.7.0